{% set name = "yarn" %}
{% set version = "1.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  # this is is calculated
  sha256: 7667eb715077b4bad8e2a832e7084e0e6f1ba54d7280dc573c8f7031a7fb093e
  # this is published on npm
  sha1: 3b82d8446b652775723900b470d966861976924b

build:
  number: 0

requirements:
  run:
    - nodejs

test:
  commands:
    - yarn --version
    - yarn versions

about:
  home: https://yarnpkg.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast, reliable, and secure dependency management.'
  description: |
      Yarn is a package manager for your code. It allows you to use and share
      code with other developers from around the world. Yarn does this
      quickly, securely, and reliably so you don’t ever have to worry.
  doc_url: https://github.com/yarnpkg/yarn/docs
  dev_url: https://github.com/yarnpkg/yarn

extra:
  recipe-maintainers:
    - dfroger
    - dougalsutherland
    - bollwyvl
