{% set name = "yarn" %}
{% set version = "4.0.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://registry.npmjs.org/@yarnpkg/cli-dist/-/cli-dist-{{ version }}.tgz
    sha256: 061d21cf42190f6a03a8b8c2242a7ee893c30845f91933ce4a4e2a65c88c02f6
  - url: https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/cli/{{ version }}/LICENSE.md
    sha256: 238d933f5c226cc197bd1dae2ad0c468e157b4cba8ed844f81549ba6db777dc4

build:
  number: 0
  noarch: generic

requirements:
  run:
    - __{{ noarch_platform }}
    # 14 not strictly accurate, but there's kind of a lot going on in the upstream...
    #
    #   >=12 <14 || 14.2 - 14.9 || >14.10.0
    #
    # ... probably will update to 16 in a month or two, even if not "accurate"
    - nodejs >=14.10.0

test:
  commands:
    - yarn --version
    - yarn --version | grep -iE "^{{ version.replace(".", "\.") }}$"
    - yarn --help
    - yarn init
    - yarn add lodash
    - yarn install --immutable --immutable-cache
  requires:
    - m2-grep  # [win]
    - git

about:
  home: https://yarnpkg.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Fast, reliable, and secure dependency management.
  dev_url: https://github.com/yarnpkg/berry
  doc_url: https://yarnpkg.com/getting-started
  description: |
    Yarn is a package manager for your code. It allows you to use and share
    code with other developers from around the world. Yarn does this
    quickly, securely, and reliably so you don't ever have to worry.

extra:
  recipe-maintainers:
    - dfroger
    - bollwyvl
