{% set name = "yarn" %}
{% set version = "1.9.1" %}
{% set sha256 = "974840b0dda99faf697fcea582737718ba7c52d34b5f1fe20f8a29bacfd762b5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-v{{ version }}.tar.gz
  url: https://github.com/yarnpkg/{{ name }}/releases/download/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  run:
    - nodejs

test:
  commands:
    - yarn --version

about:
  home: https://yarnpkg.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast, reliable, and secure dependency management.'
  description: |
      Yarn is a package manager for your code. It allows you to use and share
      code with other developers from around the world. Yarn does this
      quickly, securely, and reliably so you don’t ever have to worry.
  doc_url: https://github.com/yarnpkg/yarn/docs
  dev_url: https://github.com/yarnpkg/yarn

extra:
  recipe-maintainers:
    - dfroger
    - dougalsutherland
    - bollwyvl
