{% set name = "yarn" %}
{% set version = "1.19.0" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha1: e4fb83762849a9545f95eb077fd0905f7ddae2f0

build:
  number: 0

requirements:
  run:
    - nodejs

test:
  commands:
    - yarn --version
    - yarn versions

about:
  home: https://yarnpkg.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Fast, reliable, and secure dependency management.'
  description: |
      Yarn is a package manager for your code. It allows you to use and share
      code with other developers from around the world. Yarn does this
      quickly, securely, and reliably so you don’t ever have to worry.
  doc_url: https://github.com/yarnpkg/yarn/docs
  dev_url: https://github.com/yarnpkg/yarn

extra:
  recipe-maintainers:
    - dfroger
    - dougalsutherland
    - bollwyvl
