{% set version = "1.22.22" %}

package:
  name: yarn
  version: {{ version }}

source:
  url: https://registry.npmjs.org/yarn/-/yarn-{{ version }}.tgz
  sha256: c17d3797fb9a9115bf375e31bfd30058cac6bc9c3b8807a3d8cb2094794b51ca

build:
  number: 0
  noarch: generic
  script:
    {% if noarch_platform == "unix" %}
    - mkdir -p "$PREFIX/bin" "$PREFIX/lib"
    - cp bin/* "$PREFIX/bin"
    - cp lib/* "$PREFIX/lib"
    {% else %}
    - xcopy /s /y bin\* "%LIBRARY_BIN%"
    - xcopy /s /y lib\* "%LIBRARY_LIB%"
    {% endif%}

requirements:
  run:
    - nodejs
    - __{{ noarch_platform }}

test:
  requires:
    - m2-grep  # [win]
  commands:
    - yarn --version
    - yarn versions
    - yarn --version | grep -iE "{{ version.replace('.', '\\.') }}$"

about:
  home: https://yarnpkg.com
  license: BSD-2-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Fast, reliable, and secure dependency management.
  description: |
    Yarn is a package manager for your code. It allows you to use and share
    code with other developers from around the world. Yarn does this
    quickly, securely, and reliably so you don't ever have to worry.
  doc_url: https://github.com/yarnpkg/yarn/docs
  dev_url: https://github.com/yarnpkg/yarn

extra:
  recipe-maintainers:
    - dfroger
    - bollwyvl
