# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 4.9.1
  node_min: 18.12.0

package:
  name: yarn
  version: ${{ version }}

source:
  - url: https://registry.npmjs.org/@yarnpkg/cli-dist/-/cli-dist-${{ version }}.tgz
    sha256: 1e0045ba8c051ae53f0f024c0b37722df051bd1256cda6e9dee57d86b5e7639e
  - url: https://raw.githubusercontent.com/yarnpkg/berry/%40yarnpkg/cli/${{ version }}/LICENSE.md
    sha256: 238d933f5c226cc197bd1dae2ad0c468e157b4cba8ed844f81549ba6db777dc4

build:
  number: 0
  noarch: generic
  script:
    - if: win
      then:
        - xcopy /s /y bin\* "%LIBRARY_BIN%"
      else:
        - mkdir -p "{{ PREFIX }}/bin"
        - cp bin/* "{{ PREFIX }}/bin"
        - chmod 755 bin/*

requirements:
  run:
    - __${{ noarch_platform }}
    - nodejs >=${{ node_min }}

tests:
  - requirements:
      run:
        - nodejs ${{ node_min }}.*
    script:
      - yarn --help
      - yarn --version
      - yarn --version | node -e "process.stdin.on('data', (d) => process.exit(d.toString().indexOf('{{ version}}'))"
      - yarn init
      - yarn add lodash
      - yarn install --immutable --immutable-cache

about:
  license: BSD-2-Clause
  license_file: LICENSE.md
  summary: Fast, reliable, and secure dependency management.
  homepage: https://yarnpkg.com
  repository: https://github.com/yarnpkg/berry
  documentation: https://yarnpkg.com/getting-started
  description: |
    Yarn is a package manager for your code. It allows you to use and share
    code with other developers from around the world. Yarn does this
    quickly, securely, and reliably so you don't ever have to worry.

extra:
  recipe-maintainers:
    - dfroger
    - bollwyvl
