conda_forge_output_validation: true
conda_build:
  pkg_format: '2'
build_platform:
  osx_arm64: osx_64
github:
  branch_name: main
  tooling_branch_name: main
provider:
  linux_aarch64: azure
  linux_ppc64le: azure
  win: azure
test: native_and_emulated
